apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-task
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mlops-task
  template:
    metadata:
      labels:
        app: mlops-task
    spec:
      containers:
      - name: mlops-task
        image: mlops-task
        ports:
        - containerPort: 5000
